users:
  userList:
    - name: amir
      email: amir@gmail.com
      password: 1234
    - name: mina
      email: mina@gmail.com
      password: 1111

operators:
  operatorList:
    - name: ali
      email: alavi
      password: 4321
    - name: ahmad
      email: ahamadi@gmail.com
      password: 4444

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/navdatabase
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: ConnPool
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        jpa:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
logging:
  level:
    org.springframework.security: trace

