spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: ConnPool
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        jpa:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#

